### ISSUE TITLE
Create a melodic-devel branch and pull from my fork

### ISSUE THREAD

**Issue by DasRoteSkelett** [RethinkRobotics-opensource/rosnodejs#186]
I added a melodic-devel branch [here](https://github.com/DasRoteSkelett/rosnodejs) and changed `.travis.yml` accordingly. Please consider opening a melodic-devel branch and pull from my repo.

**Comment by chris-smith** [comment]
I've preferred to keep everything in one branch since there I don't think there are any differences between kinetic/melodic/etc that would actually impact `rosnodejs` but kinetic and xenial are also EOL... so I think the main question would be if we want to keep testing that distro and supporting people on it beyond osrf. Seems like it would be ok to me.

Any thoughts @chfritz ?

**Comment by chris-smith** [comment]
We should definitely update the node versions we test too

**Comment by chfritz** [comment]
I don't think it's critical to test against kinetic, but one thing I'll say for sure: the fact that the main branch is called `kinetic-devel` has turned people off in the past, telling me that rosnodejs only exists/works for kinetic, which of course isn't true. And I agree with your assessment that there are no real difference between those versions that impact rosnodejs. So perhaps just rename the main branch to `devel`? Testing against multiple versions should be possible without having separate branches.

**Comment by chris-smith** [comment]
Sounds good to me. I'll rename to `devel` and we can update our testing accordingly.

**Comment by DasRoteSkelett** [comment]
i will pull request then, if you like. Maybe waiting on #185 to be merged

**Comment by DasRoteSkelett** [comment]
nvm, i see #189 already does the trick
